### ISSUE TITLE
Pick a repo to make the new Main branch

### ISSUE THREAD

**Issue by bwwagner** [bwwagner/ProjectSnowCrash#2]
We need to pick a version to merge into the new master:
- [JeffSchafer ](https://github.com/bwwagner/ProjectSnowCrash/tree/JeffSchafer)
- [Mountain View Bank](https://github.com/tcspal5892/MountainViewBank)

Let me know which one you want to use and I'll make it the new main branch.

**Comment by tcspal5892** [comment]
I would stick with what jeff has.  I didnt see it before but it looks like he has some work with the data access layer i didnt.  So, in order to move forward go with it.

**Comment by jeffschafer84** [comment]
Please see my note about the profile page. I wrote everything according to
the tutorial but i think there is a syntax change from 13 to 15 i have to
look into it

**Comment by bwwagner** [comment]
I finished the migration of the JeffSchafer branch.  I could not directly merge branches because they didn't share enough history.
  Please let me know if I missed anything. Otherwise, this should be the structure of the repository moving forward.
