### ISSUE TITLE
Sql server

### ISSUE THREAD

**Issue by tcspal5892** [bwwagner/ProjectSnowCrash#4]
I don't think I was the only one having issues with the database not being scaffold-ed and created by entity framework.  Easy fix in the end.  Took me several hours to find out my machine was missing the sql server express localdb package.  Apparently it doesn't come with the full sql server express package.  Just google and download sql server localdb and you should be golden.  Also, make sure you have the entity framework nuget installed.  Then after installing that and restarting vs15, go to the package management console and type enable-migrations, add-migration %migration-name-goes-here%, then update-database

**Comment by bwwagner** [comment]
https://www.microsoft.com/en-us/server-cloud/products/sql-server-editions/sql-server-express.aspx
