### ISSUE TITLE
Slick Integration Broke Razor Bootstrap.css

### ISSUE THREAD

**Issue by bwwagner** [bwwagner/ProjectSnowCrash#6]
When the Javascript Slick (v1.5.9) object was added, somehow the Razor style was completely removed [(commit ae3b7451...)](https://github.com/bwwagner/ProjectSnowCrash/commit/ae3b7451602548ced3efa92b6384d081f7873355)  
I am looking into what could have caused this.  Jeff, @jeffschafer84 , if you can lend a hand it would be appreciated.

Additionally, the Selenium tests need to be updated to test the new elements.

**Comment by bwwagner** [comment]
Looking at the implementation of the Slick Carousel.  Gathered some info on other carousel implementations:
- [getbootstrap](https://getbootstrap.com/examples/carousel/)
- [getbootstrap with javascript](http://getbootstrap.com/javascript/)
- [w3schools](http://www.w3schools.com/bootstrap/bootstrap_carousel.asp)
- [bootstrapbay](https://bootstrapbay.com/blog/bootstrap-3-carousel-tutorial/)

**Comment by bstratton283** [comment]
What broke?

**Comment by bwwagner** [comment]
Right now it looks like settings in [slick-theme.css](https://github.com/bwwagner/ProjectSnowCrash/blob/master/SnowCrashBank/Scripts/slick-1.5.9/slick/slick-theme.css) are overriding [bootstrap.css](https://github.com/bwwagner/ProjectSnowCrash/blob/master/SnowCrashBank/Content/bootstrap.css), which was set up to control the layout for every page on the site.  I need to do some more digging to figure out which settings are being called by each element.  

Any documentation or other explanations of the Slick code that can be provided would be helpful.

Also, the Selenium UI tests will have to be updated for the carousel.

**Comment by bwwagner** [comment]
We reverted the code to 2 commits before slick was added and are going to implement a bootstrap version of the carousel.
